### ISSUE TITLE
worldGetAllPeds Crash To Desktop

### ISSUE THREAD

**Issue by Halen84** [Halen84/ScriptHookRDR2DotNet-V2#2]
For whatever reason, calling `NativeMemory.worldGetAllPeds()` will crash the game at random if the number of peds loaded is greater than 100. It's not a consistent crash, it just randomly happens if its greater than 100. The function works perfectly fine if the number of peds loaded is less than 100. Note that I haven't tested this on other pool functions, but I'd assume the same thing is happening.

This happens on all versions, including the old SHRDR2 DotNet. This also happens on both AB's scripthook and keps scripthook V2, so I **think** it's safe to assume that it's a C# issue.

Stack Trace:
```
Exception Info: System.AccessViolationException
   at RDR2DN.NativeMemory.worldGetAllPeds(Int32[], Int32)
   at RDR2.World.GetAllPeds()
   at MyProject.Main.OnTick(System.Object, System.EventArgs)
   at RDR2DN.Script.MainLoop()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
   ```
   
My only logical guess would be the array (arr) parameter. The `worldGetAllPeds` implementation is using a C-Styled array, which is somewhat different from a C# `int[]` array.

I've already spent hours trying to debug this. Tried all kinds of different marshalling methods of the parameter. Just can't get it to work. Maybe someone smarter than me can figure it out.

The only other way I have thought of fixing this was just implementing these functions in C# instead of `DllImport`ing them.

**Comment by Halen84** [comment]
Getting back to this, and a "temporary" workaround is to add `[HandleProcessCorruptedStateExceptions]` attribute to `World.GetAllPeds()` and wrap the `worldGetAllPeds()` call in a try catch with no exception parameter.

Kep told me that his scripthook v2 doesn't crash as of 1491.17, but I haven't tested it.

**Comment by Halen84** [comment]
> Still an issue here. World.GetAllPeds() keeps returning empty array.

It returns an empty array when the internal call to worldGetAllPeds failed. See comment above, or check source code.

**Comment by Halen84** [comment]
Reopened as I would like to fix this entirely instead of doing a band aid fix. Not sure if it can be fixed in C# though. Might be a problem on AB's side.

**Comment by kagikn** [comment]
Would sound silly, but I think it's because all worldGetAll function imports are missing `In` and `Out` attributes at the `arr` parameter (the In attribute is implicitly specified in this case btw). I haven't actually tested this, but I feel like that's the problem. Managed arrays should be marshalled in both ways when you call those functions. Just in case you have no idea what `In` and `Out` are, they are [InAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.inattribute?view=netframework-4.8) and [OutAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.outattribute?view=netframework-4.8) of `System.Runtime.InteropServices`. There's [a document that explains how to marshal arrays](https://learn.microsoft.com/en-us/dotnet/framework/interop/marshalling-different-types-of-arrays). Managed arrays can be moved to another addresses and that can bother you without proper marshaling or pinning when you call unmanaged functions and use managed arrays for them, so you should be careful…

It would be better if this runtime fetches pool handles without relying on AB's scripthook like how SHVDN fetches pool handles as you won't always have to use large buffer arrays in that way, but should be another topic. It would be worth noting that gameconfig.xml specifies the `CObject` pool (which `Prop` instances would use) should allocate a block of memory that can contain 3000 elements of `CObject` (yes, in RDR3, this is more than that of GTA5), though.

Edit: You're probably aware of this, but I heard some people said worldGetAll functions don't properly work in AB's scripthook (not V2) since December 2022. If that is correct, I'm sorry, I don't have set up modding environment for RDR and can't throughly inspect that, so I can't help you in this aspect soon (but still worth learning how to marshal arrays I guess?).

**Comment by Halen84** [comment]
I believe I have already tried that in the past and it didn't work, but I'll try again just to make sure. I've already tried so many different ways to marshal that array, but none of them work. Lol man I've spent HOURS on the array parameter trying to debug that shit and eventually gave up and just stuck with the `[HandleProcessCorruptedStateExceptions]` band aid fix.

Edit: Yeah no the `[Out]` and `[In]` didn't work as expected. I really appreciate the help though. Looks like I'm going to have to implement these functions in C#. Can't rely on people to switch to keps V2.

And yes, I've heard lots of people say that the worldGetAll pool functions have been broken ever since AB rewrote his ScriptHook or whatever, but I never had any issue with them at least in C++, so I'm not sure. I guess really the only fix is to use keps ScriptHook V2 unless I decide to implement them in C# instead.
